variables:
  GIT_STRATEGY: fetch

stages:
- build_test
- code
- build_deploy
- deploy
- build_docs

cache:
  paths:
  - vendor
  - build
  - docs

build_test:
  stage: build_test
  script:
  - composer clearcache
  - composer install --no-progress --no-interaction
  artifacts:
    paths:
    - vendor/

code:
  stage: code
  script:
  - composer run-script --timeout=300 --no-interaction code

build_deploy:
  stage: build_deploy
  when: manual
  script:
  - mkdir -p build
  - cp -f woocommerce-payment-qiwi.php build/
  - cp -f cacert.pem build/
  - cp -rf languages build/
  - cp -rf includes build/
  - cp -rf assets build/
  artifacts:
    paths:
    - build/

deploy:
  stage: deploy
  when: manual
  script:
  - cp -rf build/* /var/www/wordpress/public/wp-content/plugins/woocommerce-payment-qiwi/
  - cp -rf build/languages/* /var/www/wordpress/public/wp-content/languages/plugins/

build_docs:
  stage: build_docs
  when: manual
  script:
  - composer run-script --timeout=300 --no-interaction docs
  artifacts:
    paths:
    - docs/
